---
title: "Proyecto Doctorado: espacio para publicación de documentos"
author: "Carlos Schenone"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: false
    toc_depth: 5  # up to five depths of headings (specified by #, ## and ...)
    number_sections: false  # if you want number sections at each table header
    theme: united  # specifies the theme style
    highlight: tango  # specifies the syntax highlighting style 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

En este espacio se ubicarán los documentos a compartir en el contexto del proyecto Doctorado, publicado en la url <https://cschenone.github.io/>

A continuación listamos los documentos publicados:

-   Proyecto de desarrollo "*Metodología híbrida para el abordaje de la extracción de patrones en videos usando CCN y RNN*"

    El objetivo de la actividad es desarrollar un modelo para realizar la extracción de patrones en videos, aplicando redes neuronales convolucionales y redes neuronales recurrentes, con el objetivo de etiquetar los objetos y escenas del video.

-   Proyecto de desarrollo "*Metodología híbrida para el análisis de un corpus de artículos académicos*"

    El objetivo de la actividad es desarrollar una herramienta que ayude a estudiar el estado del arte de un tema de investigación, aplicando análisis bibliométrico y técnicas de revisión sistemática, aportando un conjunto de elementos que simplifiquen el análisis de un campo científico.

    -   Próximos pasos.

        El documento contiene las directrices y los siguientes pasos recomendadas para el desarrollo del artículo de investigación presentando los resultados de la investigación en "Metodología híbrida para el análisis de un corpus de artículos académicos"

-   Proyecto de investigación "*Detección de Cianobacterias"*

    El objetivo del proyecto es realizar la detección de cianobacterias utilizando técnicas de aprendizaje profundo aplicadas al procesamientos de imágenes satelitales de fuentes abiertas.

-   Proyecto de investigación "*Detección de Plagas y Malezas*"

    El objetivo del proyecto es realizar la detección de plagas y malezas utilizando técnicas de aprendizaje profundo aplicada al procesamientos de imágenes satelitales de fuentes abiertas e imágenes capturadas del sobrevuelo de drones.
