---
title: "Analizar corpus de pdfs with R"
author: "Carlos Schenone"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 5  # up to five depths of headings (specified by #, ## and ...)
    number_sections: true  # if you want number sections at each table header
    theme: united  # specifies the theme style
    highlight: tango  # specifies the syntax highlighting style  
---

# Instalar paquetes

```{r etapa1.1, echo=T, eval = F, message=FALSE, warning=FALSE}
# install.packages("stringr") # Herramientas de procesamiento de texto
# install.packages("tidytext") # Contiene herramientas para procesar texto de manera limpia e intuitiva.
# install.packages("tidyverse") # Un meta paquete que llama a otros más (dplyr, readr, purrr, etc.) que nos facilitan la lectura, procesamiento y visualización de datos
# install.packages("tm") # Herramientas de minería de texto
# install.packages("igraph") # Amplía las funciones del paquete ggplot2 del tidyverse.
# install.packages("ggraph") # Amplía las funciones del paquete ggplot2 del tidyverse. En particular, graph hará el trabajo de crear las redes semánticas
```

# Cargar librerías

```{r etapa1.2, echo=T, eval = F, message=FALSE, warning=FALSE}
#library(stringr)  
library(tidytext) # Incorpora el análisis de tokens
library(tidyverse) # Incorpora el paquete tibble
library(tm) # Incorpora stopwords
library(igraph) # Incorpora graph_from_data_frame()
library(ggraph) # Incorpora ggraph
```

# Definir la carpeta de trabajo

```{r etapa1.3, echo=T, eval = T, message=FALSE, warning=FALSE}
# you can use an url or a path that leads to a pdf document
#pdf_path <- "https://cschenone.github.io/data/PDFs/pdf0.pdf"
pdf_path <- "https://github.com/cschenone/doctorado/desarrollo/OpenAlexAPI/functions/corpus/"
#set working directorý
#pdf_path <- here::here("desarrollo","OpenAlexAPI","intermedio", "data", "PDFs","pdf0.pdf")
```

# Extrear texto del corpus {.unnumbered}

## Definir función

```{r etapa2.1, echo=T, eval = T, message=FALSE, warning=FALSE}
convertpdf2txt <- function(pdf_path){
  files <- list.files(pdf_path, full.names = TRUE)
  x <- sapply(files, function(x){
  x <- pdftools::pdf_text(x) %>%
  paste0(collapse = " ") %>%
  stringr::str_squish()
  return(x)
  })
}
```

```{r etapa2.1, echo=T, eval = T, message=FALSE, warning=FALSE}
files <- list.files(pdf_path, full.names = TRUE)
```

x <- sapply(files, function(x){
x <- pdftools::pdf_text(x) %>%
paste0(collapse = " ") %>%
stringr::str_squish()
return(x)
})


## Aplicar función para extrear texto y guardarlo en "corpus"

```{r pconv05, echo=T, eval = T, message=FALSE, warning=FALSE}
corpus <- convertpdf2txt(pdf_path)
```

## Mostrar "corpus"

```{r pconv06, echo=F, eval = T, message=FALSE, warning=FALSE}
# show data
txts %>%
  substr(start=1, stop=1000) %>%
  as.data.frame() %>%
  flextable::flextable() %>%
  flextable::set_table_properties(width = .95, layout = "autofit") %>%
  flextable::theme_zebra() %>%
  flextable::fontsize(size = 12) %>%
  flextable::fontsize(size = 12, part = "header") %>%
  flextable::align_text_col(align = "center") %>%
  flextable::set_caption(caption = "Presentación de los primeros 1000 caracteres de cada trabajo del corpus")  %>%
  flextable::border_outer()
```

## Saving the texts {.unnumbered}
```{r pconv07, echo=T, eval = F, message=FALSE, warning=FALSE}
#To save the texts in txt-files on your disc, you can simply replace the predefined location (the data folder of #your Rproject located by the string `here::here("data")` with the folder where you want to store the txt-files and #then execute the code below. Also, we will name the texts (or the txt-files if you like) as *pdftext* plus their #index number.

# set working directorý
#text_path <- here::here("desarrollo","OpenAlexAPI","intermedio", "data", "text","/")

# add names to txt files
#names(txts) <- paste0(text_path, "pdftext", 1:length(txts), sep = "")

# save result to disc
#lapply(seq_along(txts), function(i)writeLines(text = unlist(txts[i]),
#    con = paste(names(txts)[i],".txt", sep = "")))
```

